apiVersion: apps/v1
kind: Deployment
metadata:
  name: namegen
  labels:
    app: namegen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: namegen
  template:
    metadata:
      labels:
        app: namegen
    spec:
      containers:
      - name: namegen
        image: 929394210222.dkr.ecr.il-central-1.amazonaws.com/myapps/namegen:12b3c8158f44a1d2193de944724c7adce39901d1
        ports:
        - containerPort: 8080 
        env:
        - name: my-db-secret
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MONGODB_URL
              