apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
type: Opaque
data:
  username: margodb_user
  password: UzNjdXJlUEBzc3dvcmQ=
  database: namegen
  db-credentials: mongodb://margodb_user:UzNjdXJlUEBzc3dvcmQ=@mongodb/namegen