name: Main Workflow
on:
     push:
         branches:
             main
jobs:
    cicd:
        name: Deploy using aws eks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: il-central-1 

            - name: Confrim aws credentials
              run: |
                aws sts get-caller-identity

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/Amazon-ecr-login@v2

            
            - name: Build,tag & push Docker image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: myapps/namegen
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            - name: Configure eks access   
              run: |
                aws eks update-kubeconfig --region il-central-1 --name namegen-cluster 

            - name: EKS deployment
              run: |
                kubectl apply -f ./k8s-manifests/app-deployment.yaml
                kubectl apply -f ./k8s-manifests/storageclass.yaml
                kubectl apply -f ./k8s-manifests/mongodb-statefulset.yaml
                kubectl set image deployment/namegen-app namegen=929394210222.dkr.ecr.il-central-1.amazonaws.com/myapps/namegen:$IMAGE_TAG -n namegen
                kubectl rollout status deployment/namegen-app -n namegen


            - name: EKS deployment
              run: |
               kubectl apply -f ./k8s-manifests/app-deployment.yaml
               kubectl rollout status deployment/namegen-app -n namegen --timeout=90s

            - name: Print Pod Diagnostics on Failure
              if: failure() # Runs automatically if the deployment times out or fails
              run: |
                echo "================ POD STATUS ================"
                kubectl get pods -n namegen
                echo "================ POD DETAILS ================"
                kubectl describe pods -l app=namegen -n namegen
                echo "================ CONTAINER LOGS ================"
                kubectl logs -l app=namegen -n namegen --tail=100
                
                





                